# Generated by Django 5.1 on 2024-09-26 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_studentprofile_linked_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('G', 'In-Group'), ('I', 'Individual')], max_length=1)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tutorprofile')),
            ],
            options={
                'verbose_name': 'tutoring session',
                'verbose_name_plural': 'tutoring sessions',
                'db_table': 'tutoring_sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'session member',
                'verbose_name_plural': 'session members',
                'db_table': 'session_members',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
