# Generated by Django 5.1 on 2024-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_studentnotification_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='subinstance_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tutornotification',
            name='subinstance_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
