# Generated by Django 5.1 on 2024-09-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTutors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'course tutor',
                'verbose_name_plural': 'course tutors',
                'db_table': 'course_tutors',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.faculty'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'course student',
                'verbose_name_plural': 'course students',
                'db_table': 'course_students',
            },
        ),
    ]
