# Generated by Django 5.1 on 2024-09-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursetutors_course_faculty_alter_course_table_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='courses.CourseStudents', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursetutors',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursetutors',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tutorprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(through='courses.CourseTutors', to='profiles.tutorprofile'),
        ),
    ]
