# Generated by Django 5.1 on 2024-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tutortryouts_tryoutcalifications'),
        ('profiles', '0002_remove_studentprofile_linked_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursetutors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudents',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='coursetutors',
            unique_together={('course', 'tutor')},
        ),
    ]
