# Generated by Django 5.1 on 2024-09-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('posts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerhelppost',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tutorprofile'),
        ),
        migrations.AddField(
            model_name='requesthelppost',
            name='comments',
            field=models.ManyToManyField(to='posts.comment'),
        ),
        migrations.AddField(
            model_name='requesthelppost',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='requesthelppost',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
    ]
