# Generated by Django 5.1 on 2024-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_offerhelppost_comments_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pfp_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
