# Generated by Django 5.1 on 2024-09-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerhelppost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='requesthelppost',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
