# Generated by Django 5.1 on 2024-09-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_coursechat'),
        ('courses', '0002_coursetutors_course_faculty_alter_course_table_and_more'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='profiles.studentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='profiles.tutorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursechat',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursechat',
            name='members',
            field=models.ManyToManyField(related_name='course_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
