# Generated by Django 5.1 on 2024-09-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='linked_courses',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='linked_courses',
        ),
    ]
