# Generated by Django 5.1 on 2024-10-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_studentprofile_linked_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'student profile', 'verbose_name_plural': 'student profiles'},
        ),
    ]
