# Generated by Django 5.1 on 2024-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=201110919, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
