# Generated by Django 5.1 on 2024-10-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
